### PR TITLE
new book for Quasar workshop

### PR DESCRIPTION
**Pull request by borondics**

### CODE REVIEW

**Comment by markotoplak** [comment]
Ok, I'll merge, but before I think we still need to add spectroscopy chapters into this one. Perhaps we need to look at one of our last booklets and keep the order from that one.

**Comment by markotoplak** [comment]
Actually, I won't merge. It would be best not add PDFs here and changing config.tex (as it is shared) should be forbidden. I'll close and reopen a new one.

**Comment by markotoplak** [comment]
@borondics, did you perhaps forget to commit the new chapter? I do not have any chapter with that name.

**Comment by borondics** [comment]
So should we upload the PDF on the website repository?

**Comment by markotoplak** [comment]
In the end I left it here because this repo also has other PDFs in the master branch (which I think is a bad idea, but anyway).

**Pull request closed without merging**
